import { User } from "@/types/user.types";

export const userdata: User[] = [
  {
    _id: "1",
    firstName: "Biswajit",
    lastName: "Dash",
    userType: "Admin",
    companyName: "Squbix",
    companyEmail: "biswajitdash907@gmail.com",
    country: "India",
    status: "Active",
    role: "Manager",
    createdAt: "2024-10-01T10:30:00Z",
    companyWebsite: "",
    created_by: null,
    updated_by: null,
    updatedAt: "",
    __v: 0,
    industry: ""
  },
  {
    _id: "2",
    firstName: "Sneha",
    lastName: "Mohanty",
    userType: "User",
    companyName: "TechNova",
    companyEmail: "sneha.tech@example.com",
    country: "India",
    status: "Inactive",
    role: "Employee",
    createdAt: "2024-09-15T09:00:00Z",
    companyWebsite: "",
    created_by: null,
    updated_by: null,
    updatedAt: "",
    __v: 0,
    industry: ""
  },
  {
    _id: "3",
    firstName: "Sipun",
    lastName: "Nayak",
    userType: "Admin",
    companyName: "CodeWorks",
    companyEmail: "sipun@codeworks.com",
    country: "India",
    status: "Active",
    role: "Developer",
    createdAt: "2024-08-20T08:00:00Z",
    companyWebsite: "",
    created_by: null,
    updated_by: null,
    updatedAt: "",
    __v: 0,
    industry: ""
  },
  {
    _id: "4",
    firstName: "Ananya",
    lastName: "Rath",
    userType: "User",
    companyName: "WebLabs",
    companyEmail: "ananya@weblabs.com",
    country: "India",
    status: "Active",
    role: "Designer",
    createdAt: "2024-07-10T12:00:00Z",
    companyWebsite: "",
    created_by: null,
    updated_by: null,
    updatedAt: "",
    __v: 0,
    industry: ""
  }
];
