import { User } from "@/types/user.types";

export const dataConstant: User[] = [
  {
    _id: "1",
    firstName: "Biswajit",
    lastName: "Dash",
    userType: "Admin",
    companyName: "Squbix",
    companyEmail: "biswajitdash907@gmail.com",
    country: "India",
    status: "Active",
    role: "Manager",
    createdAt: "2024-10-01T10:30:00Z",
    companyWebsite: "",
    created_by: null,
    updated_by: null,
    updatedAt: "",
    category: "Productivity",
    categoryDescription: "Write des",
    toolsCount: 10,
    __v: 0,
    industry: "",
    toolname: "TaskMaster",
    submiteddate: "20/04/2025",

    // ✅ New review data
    reviewerId: "101",
    reviewerName: "Amit Kumar",
    reviewerEmail: "amitkumar@example.com",
    reviewerRole: "QA Lead",
    toolId: "T001",
    toolName: "TaskMaster"
  },
  {
    _id: "2",
    firstName: "Sneha",
    lastName: "Mohanty",
    userType: "User",
    companyName: "TechNova",
    companyEmail: "sneha.tech@example.com",
    country: "India",
    status: "Inactive",
    role: "Employee",
    createdAt: "2024-09-15T09:00:00Z",
    companyWebsite: "",
    created_by: null,
    updated_by: null,
    updatedAt: "",
    category: "Development",
    categoryDescription: "Description here",
    toolsCount: 5,
    __v: 0,
    industry: "",
    toolname: "CodeTrack",
    submiteddate: "20/04/2025",

    reviewerId: "102",
    reviewerName: "Rakesh Behera",
    reviewerEmail: "rakesh@example.com",
    reviewerRole: "Developer",
    toolId: "T002",
    toolName: "CodeTrack"
  },
  {
    _id: "3",
    firstName: "Sipun",
    lastName: "Nayak",
    userType: "Admin",
    companyName: "CodeWorks",
    companyEmail: "sipun@codeworks.com",
    country: "India",
    status: "Active",
    role: "Developer",
    createdAt: "2024-08-20T08:00:00Z",
    companyWebsite: "",
    created_by: null,
    updated_by: null,
    updatedAt: "",
    category: "UI/UX",
    categoryDescription: "Some description",
    toolsCount: 8,
    __v: 0,
    industry: "",
    toolname: "DesignFlow",
    submiteddate: "20/04/2025",

    reviewerId: "103",
    reviewerName: "Priya Singh",
    reviewerEmail: "priya.singh@example.com",
    reviewerRole: "UI Tester",
    toolId: "T003",
    toolName: "DesignFlow"
  },
  {
    _id: "4",
    firstName: "Ananya",
    lastName: "Rath",
    userType: "User",
    companyName: "WebLabs",
    companyEmail: "ananya@weblabs.com",
    country: "India",
    status: "Active",
    role: "Designer",
    createdAt: "2024-07-10T12:00:00Z",
    companyWebsite: "",
    created_by: null,
    updated_by: null,
    updatedAt: "",
    category: "Analytics",
    categoryDescription: "Category info",
    toolsCount: 6,
    __v: 0,
    industry: "",
    toolname: "SalesPulse",
    submiteddate: "20/04/2025",

    reviewerId: "104",
    reviewerName: "Manoj Patel",
    reviewerEmail: "manoj.patel@example.com",
    reviewerRole: "Data Analyst",
    toolId: "T004",
    toolName: "SalesPulse"
  },
  {
    _id: "9",
    firstName: "Test",
    lastName: "User",
    userType: "User",
    companyName: "Debug Inc.",
    companyEmail: "test@debug.com",
    country: "India",
    status: "Inactive",
    role: "Tester",
    createdAt: "2024-06-01T10:00:00Z",
    companyWebsite: "",
    created_by: null,
    updated_by: null,
    updatedAt: "",
    category: "Testing",
    categoryDescription: "Bug tracking and QA tools",
    toolsCount: 4,
    __v: 0,
    industry: "",
    toolname: "BugSniper",
    submiteddate: "20/04/2025",

    reviewerId: "105",
    reviewerName: "Rajesh Kumar",
    reviewerEmail: "rajesh.k@example.com",
    reviewerRole: "QA Engineer",
    toolId: "T005",
    toolName: "BugSniper"
  }
];
